weights: ''
cfg: models/yolov3-msa-redux.yaml
data: /home/vijay/Documents/devmk4/cs525-final/models/detectors/yolov3/data/oxford_pet.yaml
hyp: data/hyps/hyp.scratch-msa.yaml
epochs: 350
batch_size: 16
imgsz: 416
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: true
adamw: false
sync_bn: false
workers: 8
project: runs/train
name: dog_yolov3_msa_redux
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 100
freeze: 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs/train/dog_yolov3_msa_redux2
