weights: ''
cfg: models/yolov3.yaml
data: /home/vijay/Documents/devmk4/cs525-final/models/detectors/yolov3/data/voc.yaml
hyp: data/hyps/hyp.scratch-msa.yaml
epochs: 57
batch_size: 16
imgsz: 416
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: true
adamw: false
sync_bn: false
workers: 4
project: runs/train
name: voc2007_yolov3_vanilla_NO_AUG
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 1000000000
freeze: 0
save_period: -1
local_rank: -1
noaug: true
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs/train/voc2007_yolov3_vanilla_NO_AUG
